project:
  type: website

website:
  title: "Inteligența Artificială Responsabilă"
  page-footer: "Copyright 2025, Knosa"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: slide_v0.qmd
        text: Prezentare

format:
  html:
    theme: cosmo